image: registry.netresearch.de/magento-ci/ci-toolchain:latest

services:
  - docker:dind

stages:
  - analyze
  - test
  - build
  - validate
  - deploy

# Perform some pre package build checks
package-check:
  stage: analyze
  only:
    - develop
    - master
    - /^(release|hotfix)-.*$/
    - merge_requests
  script:
    - ci-check-path-length
    - ci-analyze

install-php72-ce1.9.4:
  stage: test
  variables:
    PHP_VERSION: "7.2"
    MAGENTO_TAG_VERSION: "1.9.4.0"
  extends: .installationcheck

phpunit-4.8-ce1.9.4:
  stage: test
  variables:
    PHP_VERSION: "5.6"
    MAGENTO_TAG_VERSION: "1.9.4.0"
  extends: .phpunit

phpunit-4.8-ce1.9.3:
  stage: test
  variables:
    PHP_VERSION: "5.6"
    MAGENTO_TAG_VERSION: "1.9.3.10"
  extends: .phpunit

package-build:
  stage: build
  only:
    - master
    - /^(release|hotfix)-.*$/
  script:
    - make
    - magento-tar-to-connect build/scripts/packageconfig.php
    - mv var/connect/*.tgz ${CI_PROJECT_DIR}
  artifacts:
    when: on_success
    paths:
      - ./*.zip
      - ./*.tgz

package-validate:
  stage: validate
  only:
    - master
    - /^(release|hotfix)-.*$/
  script:
    - ci-validate ./*.tgz
  dependencies:
    - package-build

# Templates for jobs running PHPUnit and Integration tests
.installationcheck:
  stage: analyze
  variables:
    MAGENTO_INSTALL_SAMPLES: "no"
  tags:
    - docker
  only:
    - develop
    - master
    - /^(release|hotfix)-.*$/
    - merge_requests
  before_script:
    - ci-install-before
  script:
    - ci-install
  after_script:
    - ci-install-after

.phpunit:
  extends: .installationcheck
  script:
    # Start Docker environment
    - ci-install
    # Run PHPUnit
    - ci-phpunit-docker phpunit.xml

github:
  stage: deploy
  when: manual
  variables:
    GIT_STRATEGY: "clone"
    VAULT_PATH: "projects/DHL/Github/module-versenden-m1"
  only:
    - master
  before_script:
    - ci-github-before
  script:
    - ci-github
